let allData = {
  config:{},
  allTags:[],
  websites:[
    {
      title:'Bell',
      url:'resounding.website',
      designer:'',
      year:'',
      imgFilename:'resounding',
      tags:[
        'community','emotions','infinite','gradient']        
    },
    {
      title:'Sinds jij dood bent…',
      url:'sindsjijdoodbent.nl',
      designer:'Moniker',
      year:'',
      imgFilename:'sindsjijdoodbent',
      tags:[
        'gradient',
        'poem',
        'writing',
      ]
    },
    {
      title:'80°',
      url:'weathergradient.com',
      designer:'',
      year:'',
      imgFilename:'weathergradient',
      tags:[
        'gradient',
        'localisation',
        'weather',
        'information',
      ]
    }
  ]
}
