let objects = [
  {
    color: "peachpuff",
    title: "1. Introduction",
    date: "July 3th",
    url: "pablo.energy",
    thumbnail: "pablo-psp.jpg",
    images: ["pablo-me.jpeg", "pablo-gijs.JPG", "pablo-dnsep.jpeg"],
    tags: ["web designer & coder", "26 yo", "UI/UX"],
    description:
      "Presentation for <i>Analogue Agency</i> of some of my web works from the last two years.",
    text: "Start!",
  },
  {
    color: "#FDD33E",
    title: "2. Ésadikoi",
    date: "June 2024",
    url: "esadikoi.netlify.app",
    thumbnail: "esadikoi-0.png",
    images: [
      "esadikoi-0.png",
      "esadikoi-5.png",
      "esadikoi-4.png",
      "esadikoi-2.png",
      "esadikoi-3.png",
    ],
    tags: ["master project", "community", "map"],
    description:
      "Platform to share events and places between the students of the ésad of Amiens.",
    text: "Next project",
    text: "Next project",
  },
  {
    color: "#FF4501",
    title: "3. The web we want",
    date: "January 2024",
    url: "thewebwewant.online",
    thumbnail: "the-web-we-want-4.png",
    images: [
      "the-web-we-want-0.png",
      "the-web-we-want-5.png",
      "the-web-we-want-1.png",
      "the-web-we-want-2.png",
      "the-web-we-want-3.png",
    ],
    tags: ["essay", "handmade", "websites"],
    description:
      "Essay about the first communities utopias and the link with contemporary designers/coders.",
    text: "Next project",
  },
  {
    color: "#485BFF",
    title: "4. Nature Go",
    date: "June 2023",
    url: "nature.go",
    thumbnail: "nature-go-0.png",
    images: [
      "nature-go-0.png",
      "nature-go-1.png",
      "nature-go-2.png",
      "nature-go-3.png",
      "nature-go-4.png",
    ],
    tags: ["ux research", "serious game", "biodiversity"],
    description:
      "Serious game for a biodiversity center, developed thought the UX research.",
    text: "Next project",
  },
  {
    color: "#EEE9E9",
    title: "5. Collaborative Narratives",
    date: "September 2024",
    url: "collaborative-narratives.online",
    thumbnail: "collaborative-narratives-0.png",
    images: [
      "collaborative-narratives-0.png",
      "collaborative-narratives-1.png",
      "collaborative-narratives-2.png",
      "collaborative-narratives-spreadsheet.png",
    ],
    tags: ["organise", "show", "cascade"],
    description:
      "Website accompanying Tim's fashion project, showing mixed references and ideas from the people working on it.",
    text: "Next project",
  },
  {
    color: "#A51919",
    title: "6. Copa Alzar",
    date: "January 2024",
    url: "copa-alzar.com",
    thumbnail: "copa-alzar-0.png",
    images: [
      "copa-alzar-intro.png",
      "copa-alzar-presentacion.png",
      "copa-alzar-galeria.png",
      "copa-alzar-vin.png",
      "copa-alzar-finale.png",
    ],
    tags: ["shop", "cgi", "commisionned"],
    description:
      "Website and CGI animation to present and sell this special wine glass.",
    text: "Next project",
  },
  {
    color: "limegreen",
    title: "7. More projects",
    date: "Last year",
    url: "pablo.energy/index",
    thumbnail: "moreno-photos.png",
    images: [
      "vendete.png",
      "vendete-cam.jpeg",
      "moreno-photos.png",
      "a-map-of-internet-2.png",
      "a-map-of-internet-3.png",
      "fils-rouges-2.png",
      "fils-rouges-1.png",
      "bg-0.png",
      "bg-1.png",
      "andrea-aguilera-rotate.png",
    ],
    tags: ["handcoded", "exposition", "family", "fun/practical"],
    description:
      "Differents projects where I invest myself on the last times... 🌏 ⚡️",
    text: "Finally...",
  },
  {
    color: "dodgerblue",
    title: "8. Conclusion",
    date: "Next year",
    url: "world.com",
    thumbnail: "pablo-psp.jpg",
    images: ["pablo-psp.jpg"],
    tags: ["next year", "internship", "new family", "the netherlands"],
    description:
      "Questions, tools, soft skills, flexibility, more about myself, about the agency...",
    text: "Restart...",
  },
];
